import Head from 'next/head'
import Layout from '@/Components/Layout'
import Image from 'next/image'
import MDP2 from "../../public/images/profile/MDP2.png"
import AnimatedText from '@/Components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/Components/icons'
import HireMe from '@/Components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/Components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nishant Verma | portfolio website</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-ccl-dark w-full min-h-screen dark:text-ccl-light'>
        <Layout className=' pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/2 md:w-full'>
              <Image src={MDP2} alt="Nishant" className=' w-full h-auto lg:hidden md:inline-block
              md:w-full ' priority
               sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw" />
            </div>  
            <div className=' w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Design is where art and Science break even." 
                className=' !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'
              />
              <p className=' my-4 text-base font-medium md:text-sm sm:text-xs'>Welcome to my digital showcase - a 
                curated collection of my passion, creativity,and expertise. 
                Explore the intersection of innovation and design as you journey through my portfolio.</p>
              <div className='flex items-center self-start mt-2 lg:self-center'> 
                <Link href="/dummy.pdf" target={"_blank"}
                className="flex items-center bg-black text-ccl-light dark:text-ccl-dark dark:bg-ccl-light
                 p-2.5 px-6 rounded-lg text-lg font-semibold  hover:bg-ccl-light duration-300
                 hover:text-ccl-dark border-2 border-transparent hover:border-ccl-dark hover:dark:bg-ccl-dark hover:dark:text-ccl-Whitish 
                 hover:dark:border-ccl-light md:p-2 md:px-4 md:text-base"
                  download={true}>Resume <LinkArrow className={"w-6 ml-1"}/></Link>

                <Link href="mailto:verma.nishant1101@gmail.com" target={"_blank"}
                className="ml-4 text-lg font-medium capitalize text-ccl-dark dark:text-ccl-Whitish underline
                 md:text-base">Contact Me</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-20 md:hidden'> 
          <Image src={lightBulb} alt='' className=' w-full h-auto'></Image>
        </div>
      </main>

    </>
  )
}
